name: Test Action CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: data
        with:
          gist_id: 9132dba40f4c806617043287a9f5d1e5
          file_name: this_week_in_rust.last_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.data.content }}" || exit 1
