name: Test Action CI

on: [push]

jobs:
  check:
    name: get data from gist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run action to get data from gist
        uses: ./
        id: data
        with:
          gist_id: 9132dba40f4c806617043287a9f5d1e5
          file_name: this_week_in_rust.last_id
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: check if gist content not empty
        run: "echo ${{ steps.data.content }} || exit 1"
